apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u9tf3jd5l-python-gitops
  description: This is GitOps manifest for u9tf3jd5l-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=u9tf3jd5l-python
    backstage.io/kubernetes-id: u9tf3jd5l-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: u9tf3jd5l-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u9tf3jd5l-python
