apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u9tf3jd5l-python
  janus-idp.io/tekton: u9tf3jd5l-python
  backstage.io/kubernetes-id: u9tf3jd5l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9tf3jd5l-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
